Add some more useful development tools
commonknowledge/wordpress-starter-template pull request #16
Opened 2023-06-28 18:30 UTC by conatus

Add some more useful development tooling to the mix.

## Development Tools

### [Create Block Theme](https://wordpress.org/plugins/create-block-theme/)

Save off block themes that you are making in the full site editor to the theme on disk. Add fonts direct from the WordPress backend.

### [Pattern Manager](https://wordpress.org/plugins/pattern-manager/)

Create WordPress patterns from within the WordPress backend. They are automatically saved to the theme on disk, with appropriate metadata and can also be modified in this way.

### [Fakerpress](https://wordpress.org/plugins/fakerpress/)

Generate a lot of dummy content to see how the website looks and feels with full content in it.

### [Yoast Duplicate Posts](https://wordpress.org/plugins/duplicate-post/)

Again for creating dummy data, this allows quick duplication of posts to fill things out.

2023-06-28 18:33 UTC, conatus commented
FYI all other developers.

2023-06-28 18:33 UTC, conatus commented
Will wait a day for feedback then merge.

2023-06-28 22:06 UTC, janbaykara requested changes
Appreciate the links and docs and so on! Just a typo to fix.

2023-06-28 22:06 UTC, janbaykara commented on README.md
> +19. Repeat steps 7 through 20, but creating a developmgent environment.
woopsie

2023-07-19 16:08 UTC, conatus commented
@janbaykara 

Boink.

2023-07-21 11:10 UTC, janbaykara approved these changes
LGTM!

2023-07-21 12:08 UTC, merged